[package]
name = "gitredditor"
version = "0.1.0"
authors = ["shimunn <>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
reqwest = "0.9.16"
structopt = "0.2.15"
serde = "1.0.90"
serde_derive = "1.0.90"
